[package]
name = "sguaba"
version = "0.9.9"
edition = "2021"
license = "MIT OR Apache-2.0"

description = "Hard to misuse rigid body transforms (aka \"spatial math\") for engineers with other things to worry about than linear algebra."
repository = "https://github.com/helsing-ai/sguaba"
keywords = ["spatial", "rigid-body", "coordinates", "coordinate-systems"]
categories = ["aerospace", "mathematics"]

[features]
default = ["serde", "approx"]
serde = ["dep:serde", "nalgebra/serde-serialize", "uom/use_serde"]
approx = ["dep:approx"]
std = []

[dependencies]
approx = { version = "0.5.1", default-features = false, optional = true }
libm = { version = "0.2.15" }
nalgebra = { version = "0.33.2", default-features = false }
serde = { version = "1.0.215", default-features = false, features = ["derive"], optional = true }
typenum = { version = "1.18.0", default-features = false }
uom = { version = "0.37.0", default-features = false, features = ["autoconvert", "si", "f64"] }

[dev-dependencies]
nav-types = "0.5.2"
rstest = "0.25.0"
serde_yaml = "0.9.34"
insta = "1.41.1"
quickcheck = "1.0.3"
